
theme: jekyll-theme-slate
title: Go-Ethereum Playground
google_analytics: UA-99577378-1
repository: sudachen/playground
excerpt_separator: <!--more-->
baseurl: /playground
github:
  repository_url: https://github.com/sudachen/Playground
relative_links:
  enabled:     true
  collections: false
kramdown:
  syntax_highlighter_opts:
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
gems:
  - jekyll-feed
  - jekyll-theme-slate
exclude:
  - Gemfile
  - Gemfile.lock


